workspace:
  base: /go/src
  path: github.com/appleboy/drone-lambda

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  lint:
    image: appleboy/golang-testing:1.9.2
    group: testing
    commands:
      - make vet
      - make lint
      - make test-vendor
      - make misspell-check

  test:
    image: appleboy/golang-testing:1.9.2
    group: testing
    commands:
      - make test
      # - make coverage

  build_linux_amd64_with_module:
    image: golang:1.11
    pull: true
    group: build
    environment:
      GO111MODULE: "on"
    commands:
      - make build_linux_amd64

  build_linux_amd64:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_amd64

  build_linux_i386:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_i386

  build_linux_arm64:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_arm64

  build_linux_arm:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_arm

  # codecov:
  #   image: robertstettner/drone-codecov
  #   secrets: [ codecov_token ]
  #   files:
  #     - coverage.txt
  #   when:
  #     event: [ push, pull_request ]

  release:
    image: appleboy/golang-testing:1.9.2
    group: release
    commands:
      - make release
    when:
      event: [ tag ]

  publish_linux_amd64:
    image: plugins/docker:17.12
    group: release
    pull: true
    repo: ${DRONE_REPO}
    secrets: [ docker_username, docker_password ]
    auto_tag: true
    auto_tag_suffix: linux-amd64
    when:
      event: [ push, tag ]
      local: false

  publish_linux_i386:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-i386
    dockerfile: Dockerfile.i386
    when:
      event: [ push, tag ]
      local: false

  publish_linux_arm64:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: Dockerfile.arm64
    when:
      event: [ push, tag ]
      local: false

  publish_linux_arm:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: Dockerfile.arm
    when:
      event: [ push, tag ]
      local: false

  github:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    files:
      - dist/release/*
    when:
      event: [ tag ]

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ success, failure ]
