name: Lint and Testing

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: "^1"
          check-latest: true
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
          args: --verbose

      - uses: hadolint/hadolint-action@v3.3.0
        name: hadolint for Dockerfile
        with:
          dockerfile: docker/Dockerfile

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25", "1.26"]
    container:
      image: golang:${{ matrix.go-version }}-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: install packages
        run: |
          apk add make bash git curl gpg

      - name: testing
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
